version: '3.7'

services:
  mysql:
    image: sunnybase/mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: mysqlpass
    expose:
      - "3306"
    volumes:
      - /data/example/mysql:/var/lib/mysql
    restart: always

